name: Gaia

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Elm
        uses: jorelali/setup-elm@v3

      - name: Cache tooling
        uses: actions/cache@v2
        with:
          path: ${HOME}/bin
          key: elm-tooling

      - name: Install tooling
        run: npm install -g elm-verify-examples
        env:
          NPM_CONFIG_PREFIX: ${HOME}

      - name: Run tests
        run: ${HOME}/bin/elm-verify-examples --run-tests